import { useState, useMemo, useRef } from "react";
import { Search, Download, Sparkles, BookOpen, ChevronRight, ArrowLeft, RotateCcw, Truck, Dumbbell, Scale, Award, Wrench, MessageCircle } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { Button } from "@/components/ui/button";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { useOrgSettings } from "@/contexts/OrgSettingsContext";
import { sopCategories, sopArticles, type SOPArticle } from "@/lib/sopData";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";
import jsPDF from "jspdf";

const iconMap: Record<string, React.ComponentType<any>> = {
  Truck, Dumbbell, Scale, Award, Wrench, MessageCircle,
};

const SOPsPage = () => {
  const [search, setSearch] = useState("");
  const [selectedCategory, setSelectedCategory] = useState<string | null>(null);
  const [selectedArticle, setSelectedArticle] = useState<SOPArticle | null>(null);
  const [viewMode, setViewMode] = useState<"library" | "flashcards">("library");
  const [flipped, setFlipped] = useState(false);
  const [flashcardIndex, setFlashcardIndex] = useState(0);
  const [generating, setGenerating] = useState(false);
  const { orgName, orgLogo } = useOrgSettings();
  const { toast } = useToast();

  // Filter articles
  const filteredArticles = useMemo(() => {
    let articles = sopArticles;
    if (selectedCategory) {
      articles = articles.filter(a => a.category === selectedCategory);
    }
    if (search.trim()) {
      const q = search.toLowerCase();
      articles = articles.filter(a =>
        a.title.toLowerCase().includes(q) ||
        a.tags.some(t => t.includes(q)) ||
        a.content.toLowerCase().includes(q) ||
        a.subcategory.toLowerCase().includes(q)
      );
    }
    return articles;
  }, [selectedCategory, search]);

  // Flashcard deck
  const flashcardDeck = useMemo(() => filteredArticles.map(a => a.flashcard), [filteredArticles]);

  const downloadPDF = (article: SOPArticle) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxWidth = pageWidth - margin * 2;
    let y = 20;

    // Header
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text(orgName || "SIOTO.AI", margin, y);
    doc.text("Standard Operating Procedure", pageWidth - margin, y, { align: "right" });
    y += 15;

    // Title
    doc.setFontSize(18);
    doc.setTextColor(30);
    doc.text(article.title, margin, y, { maxWidth });
    y += 12;

    // Category
    doc.setFontSize(10);
    doc.setTextColor(120);
    const cat = sopCategories.find(c => c.id === article.category);
    doc.text(`Category: ${cat?.label || article.category} → ${article.subcategory}`, margin, y);
    y += 10;

    // Divider
    doc.setDrawColor(200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 8;

    // Content — simple line-by-line rendering
    doc.setFontSize(11);
    doc.setTextColor(40);
    const lines = article.content.split("\n");
    for (const line of lines) {
      const cleaned = line.replace(/^#{1,3}\s/, "").replace(/\*\*/g, "").replace(/^- /, "• ");
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      if (line.startsWith("##")) {
        y += 4;
        doc.setFontSize(13);
        doc.setTextColor(30);
        const wrapped = doc.splitTextToSize(cleaned, maxWidth);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 6 + 2;
        doc.setFontSize(11);
        doc.setTextColor(40);
      } else if (cleaned.trim()) {
        const wrapped = doc.splitTextToSize(cleaned, maxWidth);
        doc.text(wrapped, margin, y);
        y += wrapped.length * 5.5;
      } else {
        y += 3;
      }
    }

    // Footer
    doc.setFontSize(8);
    doc.setTextColor(170);
    doc.text(`Generated by ${orgName || "SIOTO.AI"} — ${new Date().toLocaleDateString()}`, margin, 285);

    doc.save(`${article.title.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`);
  };

  const generateBrandedDoc = async (article: SOPArticle) => {
    setGenerating(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-sop-doc", {
        body: {
          articleTitle: article.title,
          articleContent: article.content,
          companyName: orgName || "Your Company",
        },
      });

      if (error) throw error;

      const brandedContent = data?.content || article.content;

      // Generate PDF with branded content
      const doc = new jsPDF();
      const pageWidth = doc.internal.pageSize.getWidth();
      const margin = 20;
      const maxWidth = pageWidth - margin * 2;
      let y = 20;

      doc.setFontSize(10);
      doc.setTextColor(150);
      doc.text(orgName || "Your Company", margin, y);
      doc.text("Company Policy Document", pageWidth - margin, y, { align: "right" });
      y += 15;

      doc.setFontSize(18);
      doc.setTextColor(30);
      doc.text(article.title, margin, y, { maxWidth });
      y += 12;

      doc.setDrawColor(200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 8;

      doc.setFontSize(11);
      doc.setTextColor(40);
      const lines = brandedContent.split("\n");
      for (const line of lines) {
        const cleaned = line.replace(/^#{1,3}\s/, "").replace(/\*\*/g, "").replace(/^- /, "• ");
        if (y > 270) { doc.addPage(); y = 20; }
        if (line.startsWith("##")) {
          y += 4;
          doc.setFontSize(13);
          doc.setTextColor(30);
          const wrapped = doc.splitTextToSize(cleaned, maxWidth);
          doc.text(wrapped, margin, y);
          y += wrapped.length * 6 + 2;
          doc.setFontSize(11);
          doc.setTextColor(40);
        } else if (cleaned.trim()) {
          const wrapped = doc.splitTextToSize(cleaned, maxWidth);
          doc.text(wrapped, margin, y);
          y += wrapped.length * 5.5;
        } else {
          y += 3;
        }
      }

      doc.setFontSize(8);
      doc.setTextColor(170);
      doc.text(`Generated by ${orgName || "SIOTO.AI"} for ${orgName || "Your Company"} — ${new Date().toLocaleDateString()}`, margin, 285);
      doc.save(`${orgName || "Company"}_${article.title.replace(/[^a-zA-Z0-9]/g, "_")}.pdf`);

      toast({ title: "Branded document generated!", description: "Your customized PDF has been downloaded." });
    } catch (e: any) {
      console.error("Generate branded doc error:", e);
      toast({ title: "Generation failed", description: e.message || "Could not generate branded document.", variant: "destructive" });
    } finally {
      setGenerating(false);
    }
  };

  // Render markdown-ish content
  const renderContent = (content: string) => {
    return content.split("\n").map((line, i) => {
      if (line.startsWith("## ")) return <h2 key={i} className="text-lg font-display font-bold mt-6 mb-2 text-foreground">{line.replace("## ", "")}</h2>;
      if (line.startsWith("### ")) return <h3 key={i} className="text-base font-semibold mt-4 mb-1 text-foreground">{line.replace("### ", "")}</h3>;
      if (line.startsWith("- 🛑")) return <p key={i} className="ml-4 text-sm text-destructive py-0.5">{line.replace("- ", "")}</p>;
      if (line.startsWith("- ✅")) return <p key={i} className="ml-4 text-sm text-primary py-0.5">{line.replace("- ", "")}</p>;
      if (line.startsWith("- ⚠️")) return <p key={i} className="ml-4 text-sm text-accent-foreground py-0.5">{line.replace("- ", "")}</p>;
      if (line.startsWith("- **")) {
        const match = line.match(/^- \*\*(.+?)\*\*(.*)$/);
        if (match) return <p key={i} className="ml-4 text-sm py-0.5"><strong className="text-foreground">{match[1]}</strong><span className="text-muted-foreground">{match[2]}</span></p>;
      }
      if (line.startsWith("- ")) return <p key={i} className="ml-4 text-sm text-muted-foreground py-0.5">• {line.replace("- ", "")}</p>;
      if (line.match(/^\d+\./)) return <p key={i} className="ml-4 text-sm text-muted-foreground py-0.5">{line}</p>;
      if (line.startsWith("> ")) return <blockquote key={i} className="ml-4 pl-3 border-l-2 border-primary/30 text-sm italic text-muted-foreground my-2">{line.replace("> ", "")}</blockquote>;
      if (line.trim() === "") return <div key={i} className="h-2" />;
      const formatted = line.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
      return <p key={i} className="text-sm text-muted-foreground" dangerouslySetInnerHTML={{ __html: formatted }} />;
    });
  };

  return (
    <div className="p-6 lg:p-8 space-y-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl font-display font-bold">SOPs & Policies</h1>
        <p className="text-muted-foreground text-sm mt-1">Standard operating procedures, HR policies, and quick-reference flashcards</p>
      </div>

      {/* View Toggle */}
      <Tabs value={viewMode} onValueChange={(v) => setViewMode(v as any)}>
        <TabsList>
          <TabsTrigger value="library" className="gap-2"><BookOpen size={16} /> Library</TabsTrigger>
          <TabsTrigger value="flashcards" className="gap-2"><RotateCcw size={16} /> Flashcards</TabsTrigger>
        </TabsList>

        {/* Search */}
        <div className="relative max-w-xl mt-4">
          <Search size={18} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" />
          <input
            value={search}
            onChange={e => setSearch(e.target.value)}
            placeholder="Search SOPs, policies, procedures..."
            className="w-full rounded-xl border border-input bg-card pl-10 pr-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-ring"
          />
        </div>

        {/* Library View */}
        <TabsContent value="library">
          <AnimatePresence mode="wait">
            {selectedArticle ? (
              <motion.div key="article" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}>
                <button onClick={() => setSelectedArticle(null)} className="text-sm text-primary font-medium mb-4 flex items-center gap-1 hover:underline">
                  <ArrowLeft size={14} /> Back to {selectedCategory ? sopCategories.find(c => c.id === selectedCategory)?.label : "All SOPs"}
                </button>
                <div className="flex items-start justify-between gap-4 mb-4">
                  <div>
                    <h2 className="text-xl font-display font-bold">{selectedArticle.title}</h2>
                    <p className="text-xs text-muted-foreground mt-1">{selectedArticle.subcategory}</p>
                  </div>
                  <div className="flex gap-2 shrink-0">
                    <Button size="sm" variant="outline" onClick={() => downloadPDF(selectedArticle)} className="gap-1.5">
                      <Download size={14} /> PDF
                    </Button>
                    <Button size="sm" onClick={() => generateBrandedDoc(selectedArticle)} disabled={generating} className="gap-1.5">
                      <Sparkles size={14} /> {generating ? "Generating..." : "AI Branded Doc"}
                    </Button>
                  </div>
                </div>
                <div className="bg-card border border-border rounded-xl p-6 max-w-3xl">
                  {renderContent(selectedArticle.content)}
                </div>

                {/* Flashcard for this article */}
                <div className="mt-6 max-w-md">
                  <h3 className="text-sm font-semibold mb-2 flex items-center gap-2"><RotateCcw size={14} /> Quick Quiz</h3>
                  <div
                    onClick={() => setFlipped(!flipped)}
                    className="cursor-pointer p-5 rounded-xl border border-border bg-card hover:border-primary transition-all min-h-[120px] flex items-center justify-center text-center"
                  >
                    <p className="text-sm">{flipped ? selectedArticle.flashcard.back : selectedArticle.flashcard.front}</p>
                  </div>
                  <p className="text-xs text-muted-foreground mt-2 text-center">Click to flip</p>
                </div>
              </motion.div>
            ) : selectedCategory ? (
              <motion.div key="category" initial={{ opacity: 0, x: 20 }} animate={{ opacity: 1, x: 0 }} exit={{ opacity: 0, x: -20 }}>
                <button onClick={() => setSelectedCategory(null)} className="text-sm text-primary font-medium mb-4 flex items-center gap-1 hover:underline">
                  <ArrowLeft size={14} /> Back to Categories
                </button>
                <h2 className="text-xl font-display font-bold mb-4">
                  {sopCategories.find(c => c.id === selectedCategory)?.label}
                </h2>
                {/* Subcategory groups */}
                {(() => {
                  const cat = sopCategories.find(c => c.id === selectedCategory);
                  if (!cat) return null;
                  return cat.subcategories.map(sub => {
                    const subArticles = filteredArticles.filter(a => a.subcategory === sub);
                    if (subArticles.length === 0) return null;
                    return (
                      <div key={sub} className="mb-6">
                        <h3 className="text-sm font-semibold text-muted-foreground mb-2">{sub}</h3>
                        <div className="space-y-2">
                          {subArticles.map((article, i) => (
                            <motion.div
                              key={article.id}
                              initial={{ opacity: 0, y: 8 }}
                              animate={{ opacity: 1, y: 0 }}
                              transition={{ delay: i * 0.05 }}
                              onClick={() => { setSelectedArticle(article); setFlipped(false); }}
                              className="p-4 rounded-xl border border-border bg-card hover:border-primary transition-colors cursor-pointer flex items-center justify-between"
                            >
                              <div>
                                <h4 className="font-semibold text-sm">{article.title}</h4>
                                <div className="flex gap-1.5 mt-1.5 flex-wrap">
                                  {article.tags.slice(0, 4).map(t => (
                                    <span key={t} className="text-[10px] bg-secondary text-secondary-foreground px-1.5 py-0.5 rounded">{t}</span>
                                  ))}
                                </div>
                              </div>
                              <ChevronRight size={16} className="text-muted-foreground shrink-0" />
                            </motion.div>
                          ))}
                        </div>
                      </div>
                    );
                  });
                })()}
              </motion.div>
            ) : search.trim() ? (
              /* Search results — show matching articles directly */
              <motion.div key="search-results" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                {filteredArticles.length === 0 ? (
                  <p className="text-muted-foreground text-sm">No articles match "{search}".</p>
                ) : (
                  <div className="space-y-2">
                    <p className="text-xs text-muted-foreground mb-3">{filteredArticles.length} result{filteredArticles.length !== 1 ? "s" : ""}</p>
                    {filteredArticles.map((article, i) => (
                      <motion.div
                        key={article.id}
                        initial={{ opacity: 0, y: 8 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: i * 0.03 }}
                        onClick={() => { setSelectedArticle(article); setFlipped(false); }}
                        className="p-4 rounded-xl border border-border bg-card hover:border-primary transition-colors cursor-pointer flex items-center justify-between"
                      >
                        <div>
                          <h4 className="font-semibold text-sm">{article.title}</h4>
                          <p className="text-xs text-muted-foreground mt-0.5">{sopCategories.find(c => c.id === article.category)?.label} → {article.subcategory}</p>
                          <div className="flex gap-1.5 mt-1.5 flex-wrap">
                            {article.tags.slice(0, 4).map(t => (
                              <span key={t} className="text-[10px] bg-secondary text-secondary-foreground px-1.5 py-0.5 rounded">{t}</span>
                            ))}
                          </div>
                        </div>
                        <ChevronRight size={16} className="text-muted-foreground shrink-0" />
                      </motion.div>
                    ))}
                  </div>
                )}
              </motion.div>
            ) : (
              <motion.div key="categories" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
                <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
                  {sopCategories.map((cat, i) => {
                    const Icon = iconMap[cat.icon] || BookOpen;
                    const count = sopArticles.filter(a => a.category === cat.id).length;
                    return (
                      <motion.button
                        key={cat.id}
                        initial={{ opacity: 0, y: 15 }}
                        animate={{ opacity: 1, y: 0 }}
                        transition={{ delay: i * 0.05 }}
                        onClick={() => setSelectedCategory(cat.id)}
                        className="text-left p-5 rounded-xl border border-border bg-card hover:border-primary hover:shadow-sm transition-all group"
                      >
                        <Icon size={24} className="text-primary" />
                        <h3 className="font-display font-semibold mt-3 mb-1">{cat.label}</h3>
                        <p className="text-xs text-muted-foreground line-clamp-2">{cat.description}</p>
                        <div className="flex items-center justify-between mt-3">
                          <span className="text-xs text-muted-foreground">{count} articles</span>
                          <ChevronRight size={16} className="text-muted-foreground group-hover:text-primary transition-colors" />
                        </div>
                      </motion.button>
                    );
                  })}
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </TabsContent>

        {/* Flashcard View */}
        <TabsContent value="flashcards">
          {flashcardDeck.length === 0 ? (
            <p className="text-muted-foreground text-sm">No flashcards match your search.</p>
          ) : (
            <div className="max-w-lg mx-auto mt-4">
              <p className="text-xs text-muted-foreground mb-2 text-center">
                Card {flashcardIndex + 1} of {flashcardDeck.length}
                {selectedCategory && ` — ${sopCategories.find(c => c.id === selectedCategory)?.label}`}
              </p>
              <motion.div
                key={flashcardIndex}
                initial={{ opacity: 0, rotateY: -90 }}
                animate={{ opacity: 1, rotateY: 0 }}
                className="cursor-pointer p-8 rounded-2xl border-2 border-border bg-card hover:border-primary transition-all min-h-[200px] flex items-center justify-center text-center shadow-sm"
                onClick={() => setFlipped(!flipped)}
              >
                <div>
                  <p className="text-xs text-muted-foreground mb-3">{flipped ? "ANSWER" : "QUESTION"}</p>
                  <p className="text-base font-medium">{flipped ? flashcardDeck[flashcardIndex].back : flashcardDeck[flashcardIndex].front}</p>
                </div>
              </motion.div>
              <p className="text-xs text-muted-foreground mt-3 text-center">Click card to flip</p>
              <div className="flex justify-center gap-3 mt-4">
                <Button
                  size="sm"
                  variant="outline"
                  disabled={flashcardIndex === 0}
                  onClick={() => { setFlashcardIndex(i => i - 1); setFlipped(false); }}
                >
                  Previous
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  disabled={flashcardIndex === flashcardDeck.length - 1}
                  onClick={() => { setFlashcardIndex(i => i + 1); setFlipped(false); }}
                >
                  Next
                </Button>
              </div>

              {/* Category filter in flashcard mode */}
              <div className="mt-8">
                <p className="text-xs font-semibold text-muted-foreground mb-2">Filter by category:</p>
                <div className="flex flex-wrap gap-2">
                  <button
                    onClick={() => { setSelectedCategory(null); setFlashcardIndex(0); setFlipped(false); }}
                    className={`text-xs px-3 py-1.5 rounded-lg border transition-colors ${!selectedCategory ? "bg-primary text-primary-foreground border-primary" : "border-border hover:border-primary"}`}
                  >
                    All
                  </button>
                  {sopCategories.map(cat => (
                    <button
                      key={cat.id}
                      onClick={() => { setSelectedCategory(cat.id); setFlashcardIndex(0); setFlipped(false); }}
                      className={`text-xs px-3 py-1.5 rounded-lg border transition-colors ${selectedCategory === cat.id ? "bg-primary text-primary-foreground border-primary" : "border-border hover:border-primary"}`}
                    >
                      {cat.label}
                    </button>
                  ))}
                </div>
              </div>
            </div>
          )}
        </TabsContent>
      </Tabs>
    </div>
  );
};

export default SOPsPage;
