-- ============================================================
-- SIOTO.AI Resource Content Seed Migration
-- Pre-populates Knowledge Base, Checklists, and SOPs with
-- professional content from SIOTO resource documents.
-- These are "system" records (company_id IS NULL) visible to all users.
-- ============================================================

-- ============================================================
-- KNOWLEDGE BASE ARTICLES
-- ============================================================

INSERT INTO knowledge_articles (title, category, content, is_published) VALUES

-- From: Inflatable Safety Tip Guide
('Inflatable Safety Tip Guide', 'Safety', E'## Inflatable Safety Tip Guide\n\nThis comprehensive guide covers the essential safety checks every operator must perform before, during, and after inflatable operations.\n\n### Wind & Weather Check\n- Check the weather forecast before every event\n- Monitor wind speeds throughout the day — do not operate above 25 mph winds\n- Watch for sudden weather changes including lightning, heavy rain, or hail\n- Have a written weather policy and communicate it to your team and clients\n\n### Setup\n- Inspect the setup area for debris, holes, slopes, and overhead hazards\n- Ensure adequate clearance on all sides of the inflatable (minimum 6 feet)\n- Place ground tarps or mats under the inflatable to protect the vinyl\n- Verify power source is adequate and cords are safely routed away from foot traffic\n- Confirm the blower is securely attached and the tube is properly sealed\n\n### Anchoring\n- Use appropriate anchoring for the surface type — stakes for grass, sandbags or water barrels for hard surfaces\n- Always use ALL anchor points — never skip any anchor point on the unit\n\n### Physical Inspection\n- Walk around the entire unit checking for tears, holes, loose seams, and worn areas\n- Verify all D-rings, straps, and buckles are intact and secure\n\n### Review Safety Rules & Agreement\n- Post visible safety rules signage at every event\n- Review safety rules with the client and all attendees\n- Have clients sign a safety agreement or waiver before use\n- Ensure an adult supervisor is present at all times during operation', true),

-- From: Safety Rules Poster
('Safety Rules for Inflatable Operations', 'Safety', E'## Safety Rules — Adult Supervision at All Times\n\nThese core safety rules must be posted and enforced at every event where inflatables are in operation. Print and display these rules prominently near each unit.\n\n### The 12 Essential Safety Rules\n\n1. **No toys inside the bounce house** — Foreign objects can cause injuries\n2. **No pets allowed** — Animals can damage equipment and injure children\n3. **Ensure inflatable is anchored** — All anchor points must be secured before use\n4. **Remove shoes and accessories** — Glasses, jewelry, and sharp objects must be removed\n5. **Do not operate in inclement weather** — Wind, rain, and lightning are serious hazards\n6. **Follow max capacity** — Never exceed the posted weight and occupant limits\n7. **No wrestling, tumbling, or flipping** — Rough play causes the majority of injuries\n8. **No climbing on netting walls** — Netting is not designed to support body weight\n9. **No food, drinks, gum, or silly string** — These create slip hazards and damage vinyl\n10. **Do not move the bounce house** — Never relocate a unit while inflated or occupied\n11. **No water or fire** — Keep all flames and water sources away from the unit\n12. **Do not allow kids to play behind the bounce house** — The blower area is a danger zone\n\n### Implementation Tips\n- Print these rules on a weatherproof sign for each unit\n- Review rules verbally with every client at setup\n- Include rules in your rental agreement and waiver\n- Train all staff to enforce these rules consistently', true),

-- From: Near Miss/Incident Report
('How to Properly Document Incidents and Near Misses', 'Safety', E'## How to Properly Document Incidents and Near Misses\n\nProper incident documentation protects your business, helps prevent future incidents, and demonstrates professionalism to clients and insurance providers.\n\n### When to File a Report\nFile a report for ANY of the following:\n- **Incident:** Any event where injury occurred or property was damaged\n- **Near Miss:** Any event that could have resulted in injury or damage but did not\n\nNear miss reporting is just as important as incident reporting — it helps you identify and fix hazards before someone gets hurt.\n\n### Required Information\nEvery report must capture:\n- **Type:** Near Miss or Incident (check one)\n- **Date and Time:** Exact date and time of the event\n- **Reporter Full Name:** Person completing the report\n- **Incident Address:** Full address where the event occurred\n- **Description:** Detailed account using the 5W1H method — Who was involved, What happened, When it occurred, Where exactly, Why it happened, and How it unfolded\n- **Type of Injury:** If applicable, describe the nature of the injury\n- **First Responder Status:** Was 911 or first responders called? (Yes/No)\n- **Injured Party Contact:** Full name and contact information of anyone injured\n- **Witness Information:** Names and contact details of all witnesses\n\n### Best Practices\n- Complete the report as soon as possible while details are fresh\n- Be factual and objective — avoid opinions or blame\n- Take photographs of the scene, equipment, and any injuries\n- Notify your insurance provider within 24 hours for any incident involving injury\n- Store all reports securely and review them quarterly to identify patterns', true),

-- From: Interview Questionnaire
('Interview Guide: Hiring the Right Team Members', 'HR & Hiring', E'## Interview Guide: Hiring the Right Team Members\n\nUse this structured interview guide to evaluate candidates consistently. Each category includes a question and guidance on what to look for in responses.\n\n### 1. Customer Service Focus\n**Question:** Tell me about a time you went above and beyond for a customer.\n**What to look for:** Genuine enthusiasm for helping people, specific examples, understanding that customer satisfaction drives the business.\n\n### 2. First Impression Mindset\n**Question:** How do you ensure you make a great first impression?\n**What to look for:** Awareness of appearance, punctuality, positive attitude, understanding that they represent the company brand.\n\n### 3. Reliability & Dependability\n**Question:** Describe a time when you had to show up even when you did not want to.\n**What to look for:** Commitment to showing up on time, understanding that the team depends on them, willingness to push through discomfort.\n\n### 4. Handling Responsibility\n**Question:** Tell me about a time you were trusted with an important task. How did you handle it?\n**What to look for:** Ownership mentality, attention to detail, follow-through, pride in doing quality work.\n\n### 5. Initiative\n**Question:** Give an example of a time you saw something that needed to be done and took action without being asked.\n**What to look for:** Proactive mindset, willingness to go beyond minimum requirements, problem-solving orientation.\n\n### 6. Teamwork\n**Question:** Describe a situation where you had to work closely with someone you did not get along with.\n**What to look for:** Maturity, ability to set aside personal differences, focus on the task, communication skills.\n\n### 7. Problem Solving in the Field\n**Question:** What would you do if something went wrong at an event and your manager was not available?\n**What to look for:** Calm under pressure, logical thinking, willingness to make decisions, understanding of when to escalate.\n\n### 8. Attention to Detail\n**Question:** How do you make sure you do not miss important steps in a process?\n**What to look for:** Use of checklists, systematic approach, double-checking work, understanding that details matter in safety.\n\n### 9. Work Ethic & Physical Demands\n**Question:** This job requires physical labor in all weather conditions. How do you handle that?\n**What to look for:** Realistic expectations, physical fitness awareness, positive attitude toward hard work, experience with outdoor labor.\n\n### 10. Ownership & Accountability\n**Question:** Tell me about a time you made a mistake. How did you handle it?\n**What to look for:** Honesty, willingness to admit fault, focus on learning and improvement, no blame-shifting.', true),

-- From: Training Tracking Log
('Training Certification Tracking Best Practices', 'Training', E'## Training Certification Tracking Best Practices\n\nMaintaining current training certifications for your entire team is essential for safety compliance, insurance requirements, and professional operations.\n\n### What to Track\nFor each team member, maintain records of:\n- **Employee Name** and role\n- **Training/Certification Type** (e.g., SIOTO Safety Certification, CPR/First Aid, Equipment Operation)\n- **Completion Date** — When the training was completed\n- **Expiration Date** — When the certification expires\n- **Notes** — Any special conditions, restrictions, or follow-up needed\n\n### Best Practices\n- **Review monthly:** Set a recurring calendar reminder to review all certifications\n- **30-day renewal window:** Schedule renewal training at least 30 days before expiration\n- **No expired certifications in the field:** Never allow a team member with an expired certification to work unsupervised\n- **New hire onboarding:** Ensure all required certifications are completed before the first solo assignment\n- **Digital backup:** Keep both physical and digital copies of all certificates\n- **Audit readiness:** Organize records so they can be produced quickly for insurance audits or inspections\n\n### Recommended Training Categories\n- SIOTO Safety Certification\n- CPR/First Aid\n- Equipment Setup & Takedown\n- Customer Service & Communication\n- Emergency Response Procedures\n- Vehicle & Trailer Operation\n- Weather Safety Protocols', true),

-- From: A Day In The Life
('First Day Training & Evaluation Guide', 'Training', E'## First Day Training & Evaluation Guide\n\nThe first day on the job sets the tone for a new team member''s entire career with your company. Use this structured evaluation to ensure new hires are properly assessed and supported.\n\n### Safety & Professionalism (Evaluate These 5 Areas)\n1. Did the trainee follow all safety steps during setup and operation?\n2. Can the trainee identify situations where they should refuse to set up (unsafe conditions, inadequate space, weather concerns)?\n3. Did the trainee demonstrate professionalism in appearance and communication?\n4. Did the trainee properly inspect equipment before and after use?\n5. Did the trainee follow proper anchoring and securing procedures?\n\n### Customer Experience & Success\n1. How did the trainee handle a difficult or demanding customer?\n2. How does the trainee define a successful event delivery?\n\n### Trainee Reflection (Have Them Answer)\n1. What surprised you most about the job today?\n2. What areas do you feel you need to grow in?\n3. Are you clear on what is expected of you going forward?\n\n### Manager Review\nRate the trainee on:\n- [ ] Engagement and enthusiasm level\n- [ ] Adherence to safety standards\n- [ ] Ability to handle physical demands\n- [ ] Understanding of role expectations\n\n**Manager Comments:** Document specific observations, strengths, and areas for improvement.\n\n### Follow-Up Actions\n- Schedule a check-in after the first week\n- Assign a mentor or buddy for the first month\n- Review and discuss this evaluation with the trainee within 48 hours', true),

-- From: Manager Observation Form
('Manager Field Observation Guide', 'Operations', E'## Manager Field Observation Guide\n\nRegular field observations help maintain quality standards, identify training gaps, and recognize top performers. Use this guide to conduct structured evaluations of your team in the field.\n\n### Observation Categories\n\n**Safety Compliance**\n- Is the employee following all safety protocols?\n- Are proper anchoring procedures being used?\n- Is the employee monitoring weather conditions?\n- Are safety rules posted and being enforced?\n\n**Customer Interaction**\n- Is the employee greeting customers professionally?\n- Are customer questions being answered accurately?\n- Is the employee maintaining a positive attitude?\n- Are complaints being handled appropriately?\n\n**Equipment Handling**\n- Is equipment being set up correctly and efficiently?\n- Is the employee performing pre-use inspections?\n- Is equipment being properly cleaned and stored after use?\n- Are any equipment issues being reported promptly?\n\n**Professionalism**\n- Is the employee in proper uniform/attire?\n- Is the employee punctual and prepared?\n- Is the employee representing the company brand positively?\n\n**Communication**\n- Is the employee communicating effectively with the team?\n- Are issues being escalated appropriately?\n- Is the employee providing clear instructions to customers?\n\n### Scoring & Follow-Up\n- Rate each category on a scale of 1-5\n- Document specific examples for any score below 3\n- Create action items for improvement areas\n- Schedule follow-up observation within 30 days for any employee scoring below average\n- Recognize and reward employees who consistently score 4-5', true);


-- ============================================================
-- CHECKLIST TEMPLATES
-- ============================================================

-- Checklist 1: Pre-Season Checklist (from PRESEASONCHECKLIST)
INSERT INTO checklists (title, description) VALUES
('Pre-Season Checklist', 'Comprehensive checklist to prepare your business for the upcoming season. Covers personnel, tools & equipment, and vehicles & trailers.');

INSERT INTO checklist_items (checklist_id, label, sort_order) VALUES
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Begin hiring', 1),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Contact your staff from last year', 2),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Post job openings on Social Media, Job Boards, Colleges and Universities', 3),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have an interview questionnaire?', 4),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have a training and onboarding plan in place?', 5),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Is your team Safety Trained?', 6),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have plenty of blowers for the season? (1HP, 1.5HP, 2HP, etc.)', 7),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have plenty of sandbags and stakes?', 8),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have plenty of tarps and mats?', 9),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Have you inspected your dollies?', 10),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have clips for sandbags?', 11),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Have you tested your portable generators? Do they need maintenance?', 12),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have plenty of cleaning materials (Rags, Spray Bottles, Cleaners, Disinfectants)?', 13),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Have you inspected, maintained and repaired your units? (Inflatables, Dunk Tanks, Games, Foam Machines, Concessions, etc.)', 14),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have plenty of supplies for concession machines?', 15),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do vehicles need maintenance (Oil Change, Tire Rotations, etc.)?', 16),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have the Registration and Insurance Card in each vehicle?', 17),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have a Toll Pass in each vehicle?', 18),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you have the required tools in the event of a vehicle breakdown?', 19),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Are license plates current on all vehicles?', 20),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Does trailer need any repairs?', 21),
((SELECT id FROM checklists WHERE title = 'Pre-Season Checklist' ORDER BY created_at DESC LIMIT 1), 'Do you need to restock on ratchet straps / tie down straps?', 22);


-- Checklist 2: Inflatable Safety Tip Checklist (from InflatableSafetyTipGuide)
INSERT INTO checklists (title, description) VALUES
('Inflatable Safety Tip Checklist', 'Essential safety checks every operator must perform before, during, and after inflatable operations.');

INSERT INTO checklist_items (checklist_id, label, sort_order) VALUES
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Check the weather forecast before the event', 1),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Monitor wind speeds throughout the day', 2),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Watch for sudden weather changes (lightning, heavy rain, hail)', 3),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Communicate weather policy to team and clients', 4),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Inspect setup area for debris, holes, slopes, and overhead hazards', 5),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Ensure adequate clearance on all sides (minimum 6 feet)', 6),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Place ground tarps or mats under the inflatable', 7),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Verify power source is adequate and cords are safely routed', 8),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Confirm blower is securely attached and tube is properly sealed', 9),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Use appropriate anchoring for surface type (stakes for grass, sandbags for hard surfaces)', 10),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Use ALL anchor points — never skip any', 11),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Walk around entire unit checking for tears, holes, loose seams', 12),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Verify all D-rings, straps, and buckles are intact and secure', 13),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Post visible safety rules signage at the event', 14),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Review safety rules with client and attendees', 15),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Have clients sign safety agreement or waiver', 16),
((SELECT id FROM checklists WHERE title = 'Inflatable Safety Tip Checklist' ORDER BY created_at DESC LIMIT 1), 'Ensure adult supervisor is present at all times', 17);


-- Checklist 3: Inflatable Maintenance Inspection (from InflatableMaintenanceLog)
INSERT INTO checklists (title, description) VALUES
('Inflatable Maintenance Inspection', 'Equipment inspection checklist for each inflatable unit. Check all areas and document condition.');

INSERT INTO checklist_items (checklist_id, label, sort_order) VALUES
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Inspect Entrance Area — check for tears, wear, and proper padding', 1),
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Inspect Exit Area — check for tears, wear, and proper padding', 2),
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Inspect Ramp — check for damage, secure attachment, and grip surface', 3),
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Inspect all Anchor Points — check for wear and secure attachment', 4),
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Inspect all Straps — check for fraying, stretching, and secure buckles', 5),
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Inspect all D-rings — check for rust, bending, and secure attachment', 6),
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Inspect Zipper — check for smooth operation and no missing teeth', 7),
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Inspect Velcro — check for proper adhesion and no debris', 8),
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Clean and sanitize the entire unit', 9),
((SELECT id FROM checklists WHERE title = 'Inflatable Maintenance Inspection' ORDER BY created_at DESC LIMIT 1), 'Document any damage found and schedule repairs', 10);


-- Checklist 4: First Day Trainee Evaluation (from ADAYINTHELIFE)
INSERT INTO checklists (title, description) VALUES
('First Day Trainee Evaluation', 'Structured evaluation for new team members on their first day. Covers safety, customer service, and manager assessment.');

INSERT INTO checklist_items (checklist_id, label, sort_order) VALUES
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Trainee followed all safety steps during setup and operation', 1),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Trainee can identify situations where they should refuse to set up', 2),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Trainee demonstrated professionalism in appearance and communication', 3),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Trainee properly inspected equipment before and after use', 4),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Trainee followed proper anchoring and securing procedures', 5),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Trainee handled difficult or demanding customer appropriately', 6),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Trainee can define what a successful event delivery looks like', 7),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Trainee reflected on surprises and growth areas', 8),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Trainee is clear on role expectations going forward', 9),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Manager assessed engagement and enthusiasm level', 10),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Manager assessed adherence to safety standards', 11),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Manager assessed ability to handle physical demands', 12),
((SELECT id FROM checklists WHERE title = 'First Day Trainee Evaluation' ORDER BY created_at DESC LIMIT 1), 'Manager assessed understanding of role expectations', 13);


-- Checklist 5: Manager Field Observation (from ManagerObservationForm)
INSERT INTO checklists (title, description) VALUES
('Manager Field Observation', 'Structured field observation checklist for evaluating team members on safety, customer service, equipment handling, and professionalism.');

INSERT INTO checklist_items (checklist_id, label, sort_order) VALUES
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Employee is following all safety protocols', 1),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Proper anchoring procedures are being used', 2),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Employee is monitoring weather conditions', 3),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Safety rules are posted and being enforced', 4),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Employee is greeting customers professionally', 5),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Customer questions are being answered accurately', 6),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Employee is maintaining a positive attitude', 7),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Complaints are being handled appropriately', 8),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Equipment is being set up correctly and efficiently', 9),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Employee is performing pre-use inspections', 10),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Equipment is being properly cleaned and stored after use', 11),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Equipment issues are being reported promptly', 12),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Employee is in proper uniform/attire', 13),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Employee is punctual and prepared', 14),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Employee is communicating effectively with the team', 15),
((SELECT id FROM checklists WHERE title = 'Manager Field Observation' ORDER BY created_at DESC LIMIT 1), 'Issues are being escalated appropriately', 16);


-- Checklist 6: Interview Process Checklist (from InterviewQuestionnaire)
INSERT INTO checklists (title, description) VALUES
('Interview Process Checklist', 'Structured interview evaluation covering 10 key competency areas. Use during candidate interviews to ensure consistent assessment.');

INSERT INTO checklist_items (checklist_id, label, sort_order) VALUES
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about Customer Service Focus — candidate shows enthusiasm for helping people', 1),
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about First Impression Mindset — candidate is aware of appearance and punctuality', 2),
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about Reliability & Dependability — candidate shows commitment to showing up', 3),
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about Handling Responsibility — candidate demonstrates ownership mentality', 4),
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about Initiative — candidate is proactive and goes beyond minimum', 5),
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about Teamwork — candidate can work with different personalities', 6),
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about Problem Solving in the Field — candidate stays calm under pressure', 7),
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about Attention to Detail — candidate uses systematic approach', 8),
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about Work Ethic & Physical Demands — candidate has realistic expectations', 9),
((SELECT id FROM checklists WHERE title = 'Interview Process Checklist' ORDER BY created_at DESC LIMIT 1), 'Asked about Ownership & Accountability — candidate admits mistakes and learns', 10);


-- ============================================================
-- SOPs (Standard Operating Procedures)
-- ============================================================

INSERT INTO sops (title, category, content, is_published) VALUES

('Inflatable Setup & Safety SOP', 'Safety', E'## Standard Operating Procedure: Inflatable Setup & Safety\n\n### Purpose\nTo ensure consistent, safe setup and operation of all inflatable units at every event.\n\n### Scope\nApplies to all team members involved in inflatable setup, operation, and takedown.\n\n### Procedure\n\n**Pre-Event (Day Before)**\n1. Check weather forecast for event day\n2. Confirm all equipment is loaded and inventory is complete\n3. Verify vehicle is fueled and maintenance is current\n\n**Arrival & Setup**\n1. Arrive at least 60 minutes before event start time\n2. Inspect the setup area for debris, holes, slopes, and overhead hazards\n3. Ensure minimum 6 feet clearance on all sides\n4. Lay ground tarps or mats\n5. Unroll and position the inflatable unit\n6. Connect blower and verify secure attachment\n7. Inflate the unit and perform full physical inspection\n8. Anchor using ALL anchor points — stakes for grass, sandbags for hard surfaces\n9. Post safety rules signage\n10. Review safety rules with client\n11. Collect signed waiver/safety agreement\n\n**During Operation**\n1. Maintain adult supervision at all times\n2. Enforce all 12 safety rules\n3. Monitor weather conditions continuously\n4. Check anchor points every 30 minutes\n5. Monitor occupancy — never exceed max capacity\n\n**Takedown**\n1. Ensure all participants have exited\n2. Turn off and disconnect blower\n3. Remove all anchoring\n4. Clean and sanitize the unit\n5. Deflate, fold, and roll properly\n6. Load equipment and verify nothing is left behind\n7. Complete post-event inspection report', true),

('Incident Response SOP', 'Safety', E'## Standard Operating Procedure: Incident Response\n\n### Purpose\nTo ensure proper handling of any incident or near miss during operations.\n\n### Scope\nApplies to all team members present at any event.\n\n### Procedure\n\n**Immediate Response (First 5 Minutes)**\n1. Ensure the safety of all participants — stop operations if necessary\n2. Assess the situation — determine if medical attention is needed\n3. Call 911 if there is any injury requiring medical attention\n4. Administer first aid if trained and appropriate\n5. Secure the area to prevent further incidents\n\n**Documentation (Within 1 Hour)**\n1. Complete a Near Miss/Incident Report form\n2. Record: Type (Near Miss or Incident), Date, Time, Location\n3. Document full description using 5W1H method (Who, What, When, Where, Why, How)\n4. Record type of injury if applicable\n5. Note whether first responders were called\n6. Collect contact information for injured party\n7. Collect contact information for all witnesses\n8. Take photographs of the scene, equipment, and any injuries\n\n**Notification (Within 24 Hours)**\n1. Notify your direct supervisor/manager immediately\n2. Notify the company owner within 4 hours\n3. Contact insurance provider within 24 hours for any injury incident\n4. File report in the company incident tracking system\n\n**Follow-Up (Within 1 Week)**\n1. Review the incident with the full team\n2. Identify root cause and contributing factors\n3. Implement corrective actions to prevent recurrence\n4. Update SOPs or checklists if needed\n5. Follow up with injured party if applicable', true),

('Pre-Season Preparation SOP', 'Operations', E'## Standard Operating Procedure: Pre-Season Preparation\n\n### Purpose\nTo ensure the business is fully prepared before the busy season begins.\n\n### Scope\nApplies to business owners and managers responsible for seasonal operations.\n\n### Procedure\n\n**Personnel (8-12 Weeks Before Season)**\n1. Begin hiring process — post job openings on Social Media, Job Boards, Colleges, and Universities\n2. Contact staff from last year to confirm availability\n3. Prepare interview questionnaire using the SIOTO Interview Guide\n4. Develop training and onboarding plan\n5. Schedule SIOTO Safety Training for all team members (group pricing available)\n6. Complete all training certifications before first event\n\n**Tools & Equipment (6-8 Weeks Before Season)**\n1. Inventory all blowers (1HP, 1.5HP, 2HP) and order replacements\n2. Stock sandbags, stakes, and clips\n3. Stock tarps and mats\n4. Inspect all dollies and repair/replace as needed\n5. Test all portable generators and schedule maintenance\n6. Stock cleaning materials (rags, spray bottles, cleaners, disinfectants)\n7. Inspect, maintain, and repair all units (inflatables, dunk tanks, games, foam machines, concessions)\n8. Stock supplies for concession machines\n\n**Vehicles & Trailers (4-6 Weeks Before Season)**\n1. Schedule vehicle maintenance (oil change, tire rotations, etc.)\n2. Verify Registration and Insurance Card in each vehicle\n3. Install/activate Toll Pass in each vehicle\n4. Stock breakdown tools in each vehicle\n5. Verify license plates are current on all vehicles\n6. Inspect trailers and schedule repairs\n7. Stock ratchet straps and tie-down straps\n\n**Final Checks (2 Weeks Before Season)**\n1. Complete all checklist items above\n2. Conduct team meeting to review SOPs and safety procedures\n3. Run a practice setup/takedown with the full team\n4. Verify insurance coverage is current and adequate\n5. Test all booking and scheduling systems', true);
